### PR TITLE
awam2m: Update to 1.10 version

### PR DESCRIPTION
**Pull request by pratik-prajapati-imgtec**
Also update binary path in init scripts.

Signed-off-by: Pratik Prajapati Pratik.Prajapati@imgtec.com

### CODE REVIEW

**Comment by nikhil-zinjurde-imgtec** [comment]
Package version is not updated in the Makefile

include $(TOPDIR)/rules.mk
 PKG_NAME:=awalwm2m
 PKG_VERSION:=0.1.7
 #PKG_VERSION:=master
 PKG_RELEASE:=1
PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)-$(PKG_VERSION)

**Comment by abhijit-mahajani-imgtec** [comment]
awalwm2m not awam2m in the commit message.

**Comment by abhijit-mahajani-imgtec** [comment]
https://github.com/IMGCreator/openwrt-feeds/pull/22 is moving the awalwm2m into IMGCreator/openwrt-feeds so that it awalwm2m gets added by default. so please add your changes into there itself.

**Comment by abhijit-mahajani-imgtec** [comment]
https://github.com/IMGCreator/openwrt-feeds/pull/26 is updating awalwm2m to 0.1.10 so closing this one.

**Pull request closed without merging**
